# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
# If required then check the above URL to get all the possible options available.

#spring.profiles.active=dev #In real life avoid this way to set the active profile as any change by mistake can cause big issue
                            #in production, so better to set it in the Run command of the application as -Dspring.profiles.active=dev